# Generated by Django 2.2 on 2019-04-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='station',
        ),
        migrations.AlterField(
            model_name='post',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.Station', verbose_name='Станция'),
        ),
    ]
