# Generated by Django 2.2 on 2019-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190419_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default='00:00:00:00:00', max_length=50, verbose_name='UID'),
        ),
    ]
