# Generated by Django 2.2 on 2019-04-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190430_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255, verbose_name='Data')),
            ],
        ),
    ]
