# Generated by Django 2.2 on 2019-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190514_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(default=1, verbose_name='ИД'),
        ),
    ]
