# Generated by Django 2.2 on 2019-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_station_station_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMessage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='station',
            name='ip',
        ),
        migrations.AddField(
            model_name='post',
            name='mac_uid',
            field=models.IntegerField(default=0, unique=True, verbose_name='MAC UID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.CharField(max_length=200, unique=True, verbose_name='Данные карты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Контроллер'), (1, 'Веб-приложение'), (2, 'Купюроприемник')], default=1, verbose_name='Инициатор транзакции'),
        ),
    ]
