# Generated by Django 2.2 on 2019-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190515_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mac_uid',
            field=models.CharField(max_length=10, unique=True, verbose_name='MAC UID'),
        ),
    ]
