# Generated by Django 2.2 on 2019-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190515_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='info',
            field=models.TextField(blank=True, max_length=200, verbose_name='Информация'),
        ),
    ]
