# Generated by Django 2.2 on 2019-08-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_station_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='station',
            name='course',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Курс (балл/руб)'),
        ),
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.CharField(max_length=200, verbose_name='Данные карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.Partner', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='data',
            field=models.CharField(max_length=200, verbose_name='Данные Клиента'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название организации Клиента'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app.Card', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app.Partner', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app.Post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_time',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app.Station', verbose_name='Станция'),
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100, verbose_name='Кому')),
                ('annotation', models.CharField(blank=True, max_length=150, verbose_name='Примечание')),
                ('exec_type', models.SmallIntegerField(choices=[(0, 'Не проведен'), (1, 'Проведен')], default=0, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма начисления')),
                ('annotation', models.CharField(blank=True, max_length=150, verbose_name='Примечание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.Contractor', verbose_name='Контрагент')),
            ],
        ),
    ]
