# Generated by Django 2.2 on 2019-11-29 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191118_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний раз отвечал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Данные карты'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название организации контрагента'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название клиента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Номер поста'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='annotation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
    ]
