# Generated by Django 2.2 on 2019-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EposPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='erip_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ЕРИП Счет'),
        ),
    ]
