# Generated by Django 2.2 on 2019-12-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191212_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EposPayment',
        ),
    ]
