# Generated by Django 2.2 on 2019-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_epospayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epospayment',
            options={'verbose_name': 'Платеж физ. лица', 'verbose_name_plural': 'Платежи физ. лиц'},
        ),
        migrations.AddField(
            model_name='epospayment',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
