# Generated by Django 2.2 on 2019-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191213_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='epospayment',
            name='payment_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ИД платежа'),
            preserve_default=False,
        ),
    ]
