# Generated by Django 2.2 on 2020-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191219_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_notify',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_notify_email',
            field=models.BooleanField(default=False, verbose_name='Уведомлять Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_notify_phone',
            field=models.BooleanField(default=False, verbose_name='Уведомлять телефон'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Контроллер'), (1, 'Веб-приложение'), (2, 'Купюроприемник'), (3, 'EPOS платеж')], default=1, verbose_name='Инициатор транзакции'),
        ),
    ]
